name: d_dialog
description: Dialog material widget with blur background and popup animation
version: 1.0.2
homepage: https://github.com/dwikyhardi/custom-flutter-dialog


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0